### ISSUE TITLE
32-bit Library Dependencies needed for PHP7_i686: libicudata.so.67 libicui18n.so.67 libicuio.so.67 libicuuc.so.67

### ISSUE THREAD

**Issue by TechniQTeam** [rdhoni/php7#1]
Can you please Share the following 32-bit Library Dependencies needed for PHP7_i686: libicudata.so.67, libicui18n.so.67, libicuio.so.67 and libicuuc.so.67.

Because the Library Dependencies that you have shared are for 64-bit aarch64 architecture. But My Termux needs the Library Dependencies for 32-bit i686 architecture to install PHP7_i686 Successfully.

**Comment by rdhoni** [comment]
i don't have library 32-bit
